project_id = "fgfxozvcibhuqgkjywtr"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323
enabled = true

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_signup = true

[storage]
file_size_limit = "50MiB"

[edge_functions]
enabled = true
port = 54324

# Local development: run `supabase db push` to apply migrations defined in /supabase/migrations
